=== gonzaleztroyano/asir1-lm-xslt-final/PracticaGlobal-XML2-PabloGonzalez-LM-1ASIR.xsd
<?xml version="1.0" encoding="ISO-8859-1"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">

<!-- ================================== -->
<!--           Definimos Raiz           -->
<!-- ================================== -->
<xsd:element name="inmuebles">
	<xsd:complexType>
		<xsd:sequence>
			<xsd:element ref="inmueble" maxOccurs="unbounded"/>
		</xsd:sequence>
	</xsd:complexType>
</xsd:element>

<!-- ====================================== -->
<!--         Definimos TIPOS SIMPLES        -->
<!-- ====================================== -->
<xsd:simpleType name="TipoSimple">
	<xsd:restriction base="xsd:string">
		<xsd:minLength value="1"/>
		<xsd:maxLength value="150"/>
	</xsd:restriction>
</xsd:simpleType>
<xsd:simpleType name="TipoPrecio">
	<xsd:restriction base="xsd:decimal">
		<xsd:totalDigits value="10"/>
		<xsd:fractionDigits value="2"/>
	</xsd:restriction>
</xsd:simpleType>
<xsd:simpleType name="TipoMetros2">
	<xsd:restriction base="xsd:positiveInteger">
		<xsd:totalDigits value="5"/>
	</xsd:restriction>
</xsd:simpleType>
<xsd:simpleType name="TipoCCAA">
	<xsd:restriction base="xsd:string">
		<xsd:enumeration value="Andalucia"/>
		<xsd:enumeration value="Aragon"/>
		<xsd:enumeration value="Asturias"/>
		<xsd:enumeration value="Baleares"/>
		<xsd:enumeration value="Canarias"/>
		<xsd:enumeration value="Cantabria"/>
		<xsd:enumeration value="Castilla-LaMancha"/>
		<xsd:enumeration value="Castilla y Leon"/>
		<xsd:enumeration value="Catalunya"/>
		<xsd:enumeration value="Comunidad Valenciana"/>
		<xsd:enumeration value="Extremadura"/>
		<xsd:enumeration value="Galicia"/>
		<xsd:enumeration value="La Rioja"/>
		<xsd:enumeration value="Comunidad de Madrid"/>
		<xsd:enumeration value="Murcia"/>
		<xsd:enumeration value="Navarra"/>
		<xsd:enumeration value="Pais Vasco"/>
	</xsd:restriction>
</xsd:simpleType>
<xsd:simpleType name="TipoCodigoPostal">
	<xsd:restriction base="xsd:positiveInteger">
		<xsd:totalDigits value="5"/>
	</xsd:restriction>
</xsd:simpleType>
<xsd:simpleType name="TipoLuminosidad">
	<xsd:restriction base="xsd:string">
		<xsd:enumeration value="Alta"/>
		<xsd:enumeration value="Media"/>
		<xsd:enumeration value="Baja"/>
		<xsd:enumeration value="Nula"/>
	</xsd:restriction>
</xsd:simpleType>
<xsd:simpleType name="TipoBooleano">
	<xsd:restriction base="xsd:string">
		<xsd:enumeration value="Si"/>
		<xsd:enumeration value="No"/>
	</xsd:restriction>
</xsd:simpleType>
<xsd:simpleType name="TipoCalif">
	<xsd:restriction base="xsd:string">
		<xsd:enumeration value="A"/>
		<xsd:enumeration value="B"/>
		<xsd:enumeration value="C"/>
		<xsd:enumeration value="D"/>
		<xsd:enumeration value="E"/>
		<xsd:enumeration value="F"/>
		<xsd:enumeration value="G"/>
	</xsd:restriction>
</xsd:simpleType>
<xsd:simpleType name="TipoTipoInmueble">
	<xsd:restriction base="xsd:string">
		<xsd:enumeration value="Vivienda"/>
		<xsd:enumeration value="Local"/>
		<xsd:enumeration value="Almacen"/>
		<xsd:enumeration value="Suelo"/>
	</xsd:restriction>
</xsd:simpleType>
<xsd:simpleType name="TipoTelefono">
	<xsd:restriction base="xsd:positiveInteger">
		<xsd:totalDigits value="9"/>
	</xsd:restriction>
</xsd:simpleType>
<xsd:simpleType name="TipoNIF">
<xsd:restriction base="xsd:string">
		<xsd:minLength value="9"/>
		<xsd:maxLength value="9"/>
	</xsd:restriction>
</xsd:simpleType>
<xsd:simpleType name="TipoTipoPropi">
	<xsd:restriction base="xsd:string">
		<xsd:enumeration value="Particular"/>
		<xsd:enumeration value="Empresa"/>
	</xsd:restriction>
</xsd:simpleType>
<xsd:simpleType name="TipoEleccionDisponibilidad">
	<xsd:restriction base="xsd:string">
		<xsd:enumeration value="Completa"/>
		<xsd:enumeration value="Nunca"/>
		<xsd:enumeration value="Ocasionalmente"/>
	</xsd:restriction>
</xsd:simpleType>
<xsd:simpleType name="TipoDia">
	<xsd:restriction base="xsd:positiveInteger">
		<xsd:minInclusive value="1"/>
		<xsd:maxInclusive value="31"/>
	</xsd:restriction>
</xsd:simpleType>
<xsd:simpleType name="TipoMes">
	<xsd:restriction base="xsd:string">
		<xsd:enumeration value="Enero"/>
		<xsd:enumeration value="Febrero"/>
		<xsd:enumeration value="Marzo"/>
		<xsd:enumeration value="Abril"/>
		<xsd:enumeration value="Mayo"/>
		<xsd:enumeration value="Junio"/>
		<xsd:enumeration value="Julio"/>
		<xsd:enumeration value="Agosto"/>
		<xsd:enumeration value="Septiembre"/>
		<xsd:enumeration value="Octubre"/>
		<xsd:enumeration value="Noviembre"/>
		<xsd:enumeration value="Diciembre"/>
	</xsd:restriction>
</xsd:simpleType>
<xsd:simpleType name="TipoAnio">
	<xsd:restriction base="xsd:integer">
		<xsd:totalDigits value="4"/>
	</xsd:restriction>
</xsd:simpleType>
<!-- ====================================== -->
<!--   Definimos ELEMENTOS DE TIPO SIMPLES  -->
<!-- ====================================== -->
<xsd:element name="forma_adquisicion" type="TipoSimple"/>
<xsd:element name="precio" type="TipoPrecio"/>
<xsd:element name="metros2" type="TipoMetros2"/>
<xsd:element name="calle" type="TipoSimple"/>
<xsd:element name="localidad" type="TipoSimple"/>
<xsd:element name="CCAA" type="TipoCCAA"/>
<xsd:element name="cod_postal" type="TipoCodigoPostal"/>
<xsd:element name="n_habitaciones" type="xsd:positiveInteger"/>
<xsd:element name="n_banios" type="xsd:positiveInteger"/>
<xsd:element name="luminosidad" type="TipoLuminosidad"/>
<xsd:element name="terraza" type="TipoBooleano"/>
<xsd:element name="amueblado" type="TipoBooleano"/>
<xsd:element name="calif_energetica" type="TipoCalif"/>
<xsd:element name="nombre" type="TipoSimple"/>
<xsd:element name="apellidos" type="TipoSimple"/>
<xsd:element name="telefono" type="TipoTelefono"/>
<xsd:element name="email" type="TipoSimple"/>
<xsd:element name="nif" type="TipoNIF"/>
<xsd:element name="cif" type="TipoNIF"/>
<xsd:element name="scan_data" type="xsd:string"/>
<xsd:element name="dia" type="TipoDia"/>
<xsd:element name="mes" type="TipoMes"/>
<xsd:element name="anio" type="TipoAnio"/>
<xsd:element name="cantidad" type="TipoPrecio"/>
<xsd:element name="hora" type="TipoSimple"/>
<xsd:element name="cliente" type="TipoSimple"/>
<!-- ====================================== -->
<!--           Definimos ATRIBUTOS          -->
<!-- ====================================== -->
<xsd:attribute name="desc" type="TipoSimple"/>
<xsd:attribute name="tipo_inmueble" type="TipoTipoInmueble"/>
<xsd:attribute name="id_inmueble" type="xsd:ID"/>
<xsd:attribute name="id_propi" type="TipoSimple"/>
<xsd:attribute name="tipo_propi" type="TipoTipoPropi"/>
<xsd:attribute name="id_emple" type="TipoSimple"/>
<xsd:attribute name="id_puja" type="xsd:ID"/>
<!-- ====================================== -->
<!--        Definimos TIPOS COMPLEJOS       -->
<!-- ====================================== -->
<xsd:complexType name="TipoInmueble">
	<xsd:sequence>
		<xsd:element ref="datos_inmueble"/>
		<xsd:element ref="datos_propi"/>
		<xsd:element ref="datos_gestor"/>
		<xsd:element ref="datos_subasta" minOccurs="0"/>
	</xsd:sequence>
</xsd:complexType>
<xsd:complexType name="TipoDatos_Inmueble">
	<xsd:sequence>
		<xsd:element ref="forma_adquisicion"/>
		<xsd:element ref="precio"/>
		<xsd:element ref="metros2"/>
		<xsd:element ref="ubicacion"/>
		<xsd:element ref="descripcion"/>
		<xsd:element ref="fotos_inmu"/>
	</xsd:sequence>
	<xsd:attribute ref="tipo_inmueble" use="required"/>
	<xsd:attribute ref="id_inmueble" use="required"/>
</xsd:complexType>
<xsd:complexType name="TipoUbicacion">
	<xsd:sequence>
		<xsd:element ref="calle"/>
		<xsd:element ref="localidad"/>
		<xsd:element ref="CCAA"/>
		<xsd:element ref="cod_postal"/>
	</xsd:sequence>
</xsd:complexType>
<xsd:complexType name="TipoDescripcion">
	<xsd:sequence>
		<xsd:element ref="n_habitaciones"/>
		<xsd:element ref="n_banios"/>
		<xsd:element ref="luminosidad"/>
		<xsd:element ref="terraza"/>
		<xsd:element ref="amueblado"/>
		<xsd:element ref="calif_energetica"/>
	</xsd:sequence>
</xsd:complexType>
<xsd:complexType name="TipoFotos_inmu">
	<xsd:sequence>
		<xsd:element ref="foto_inmu" maxOccurs="15"/>
	</xsd:sequence>
</xsd:complexType>
<xsd:complexType name="TipoFoto_inmu" mixed="true">
	<xsd:attribute ref="desc" use="optional"/>
</xsd:complexType>
<xsd:complexType name="TipoDatos_Propi">
	<xsd:sequence>
		<xsd:element ref="nombre"/>
		<xsd:element ref="apellidos"/>
		<xsd:element ref="datos_contacto"/>
		<xsd:choice>
			<xsd:element ref="datos_particular"/>
			<xsd:element ref="datos_empresa"/>
		</xsd:choice>
	</xsd:sequence>
	<xsd:attribute ref="tipo_propi" use="required"/>
	<xsd:attribute ref="id_propi" use="required"/>
</xsd:complexType>
<xsd:complexType name="TipoDatos_Contacto">
	<xsd:sequence>
		<xsd:element ref="telefono"/>
		<xsd:element ref="email"/>
	</xsd:sequence>
</xsd:complexType>
<xsd:complexType name="TipoDatos_Particular">
	<xsd:sequence>
		<xsd:element ref="nif"/>
		<xsd:element ref="scan_data"/>
	</xsd:sequence>
</xsd:complexType>
<xsd:complexType name="TipoDatos_Empresa">
	<xsd:sequence>
		<xsd:element ref="cif"/>
		<xsd:element ref="scan_data"/>
	</xsd:sequence>
</xsd:complexType>
<xsd:complexType name="TipoDatos_Gestor">
	<xsd:sequence>
		<xsd:element ref="datos_emple"/>
		<xsd:element ref="foto_emple"/>
		<xsd:element ref="disponibilidad"/>
	</xsd:sequence>
	<xsd:attribute ref="id_emple" use="required"/>
</xsd:complexType>
<xsd:complexType name="TipoDisponibilidad">
	<xsd:sequence>
		<xsd:element name="l-v-m" type="TipoEleccionDisponibilidad"/>
		<xsd:element name="l-v-t" type="TipoEleccionDisponibilidad"/>
		<xsd:element name="s-m" type="TipoEleccionDisponibilidad"/>
	</xsd:sequence>
</xsd:complexType>
<xsd:complexType name="TipoDatos_Subasta">
	<xsd:sequence>
		<xsd:element ref="puja" maxOccurs="unbounded"/>
	</xsd:sequence>
</xsd:complexType>
<xsd:complexType name="TipoPuja">
	<xsd:sequence>
		<xsd:element ref="cliente"/>
		<xsd:element ref="timestamp"/>
		<xsd:element ref="cantidad"/>
	</xsd:sequence>
	<xsd:attribute ref="id_puja" use="required"/>
</xsd:complexType>
<xsd:complexType name="TipoTimestamp">
	<xsd:sequence>
		<xsd:element ref="dia"/>
		<xsd:element ref="mes"/>
		<xsd:element ref="anio"/>
		<xsd:element ref="hora"/>
	</xsd:sequence>
</xsd:complexType>
<!-- ====================================== -->
<!--  Definimos ELEMENTOS DE TIPO COMPLEJO  -->
<!-- ====================================== -->
<xsd:element name="inmueble" type="TipoInmueble"/>
<xsd:element name="datos_inmueble" type="TipoDatos_Inmueble"/>
<xsd:element name="ubicacion" type="TipoUbicacion"/>
<xsd:element name="descripcion" type="TipoDescripcion"/>
<xsd:element name="fotos_inmu" type="TipoFotos_inmu"/>
<xsd:element name="foto_inmu" type="TipoFoto_inmu"/>
<xsd:element name="datos_contacto" type="TipoDatos_Contacto"/>
<xsd:element name="datos_propi" type="TipoDatos_Propi"/>
<xsd:element name="datos_particular" type="TipoDatos_Particular"/>
<xsd:element name="datos_empresa" type="TipoDatos_Empresa"/>
<xsd:element name="datos_gestor" type="TipoDatos_Gestor"/>
<xsd:element name="datos_emple" type="TipoDatos_Contacto"/>
<xsd:element name="foto_emple" type="TipoFoto_inmu"/>
<xsd:element name="disponibilidad" type="TipoDisponibilidad"/>
<xsd:element name="puja" type="TipoPuja"/>
<xsd:element name="datos_subasta" type="TipoDatos_Subasta"/>
<xsd:element name="timestamp" type="TipoTimestamp"/>
</xsd:schema>

=== gonzaleztroyano/asir1-lm-xslt-final/PrácticaGlobal-XML-2PabloGonzález-LM-1ASIR.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>

<!-- Nombre del alumno:   Pablo González -->
<!-- Curso del alumno:    1ºASIR (A) -->
<!-- Fecha modificación:  15/05/2021 -->
<!-- Version:             v4.0       -->
<!--NOTAS
		v4.0   -   Se actualiza el documento para añadir información sobre más alquileres y datos respecto a estos. 
		v4.1   -   Añadir más inmuebles.
-->

<inmuebles xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="PracticaGlobal-XML2-PabloGonzalez-LM-1ASIR.xsd" inmobiliaria="VILLABLANCA">
	<!--
	<inmueble>
		<datos_inmueble tipo_inmueble="" id_inmueble="">
			<forma_adquisicion></forma_adquisicion>
			<precio></precio>
			<metros2></metros2>
			<ubicacion>
				<calle></calle>
				<localidad></localidad>
				<CCAA></CCAA>
				<cod_postal></cod_postal>
			</ubicacion>
			<descripcion>
				<n_habitaciones></n_habitaciones>
				<n_banios></n_banios>
				<luminosidad></luminosidad>
				<terraza></terraza>
				<amueblado></amueblado>
				<calif_energetica></calif_energetica>
			</descripcion>
			<fotos_inmu></fotos_inmu>
		</datos_inmueble>
		<datos_propi id_propi="" tipo_propi="">
			<nombre></nombre>
			<apellidos></apellidos>
			<datos_contacto>
				<telefono></telefono>
				<email></email>
			</datos_contacto>
			<datos_empresa>
				<cif></cif>
				<scan_data></scan_data>
			</datos_empresa>
			<datos_particular>
				<nif></nif>
				<scan_data></scan_data>
			</datos_particular>
		</datos_propi>
		<datos_gestor id_emple="">
			<datos_emple>
				<telefono></telefono>
				<email></email>
			</datos_emple>
			<foto_emple></foto_emple>
			<disponibilidad>
				<l-v-m></l-v-m>
				<l-v-t></l-v-t>
				<s-m></s-m>
			</disponibilidad>
		</datos_gestor>
		<datos_subasta>
			<puja id_puja="">
				<cliente></cliente>
				<timestamp></timestamp>
				<cantidad></cantidad>
			</puja>
		</datos_subasta>
	</inmueble>
	-->
	<inmueble>
		<datos_inmueble tipo_inmueble="Vivienda" id_inmueble="v1">
			<forma_adquisicion>Alquiler con 3 meses de fianza</forma_adquisicion>
			<precio>700</precio>
			<metros2>40</metros2>
			<ubicacion>
				<calle>Mayor, 1</calle>
				<localidad>Madrid</localidad>
				<CCAA>Comunidad de Madrid</CCAA>
				<cod_postal>28001</cod_postal>
			</ubicacion>
			<descripcion>
				<n_habitaciones>2</n_habitaciones>
				<n_banios>1</n_banios>
				<luminosidad>Alta</luminosidad>
				<terraza>No</terraza>
				<amueblado>Si</amueblado>
				<calif_energetica>C</calif_energetica>
			</descripcion>
			<fotos_inmu>
				<foto_inmu desc="PEPE">"./content/v1.png"</foto_inmu>
			</fotos_inmu>
		</datos_inmueble>
		<datos_propi id_propi="p1" tipo_propi="Particular">
			<nombre>Marta</nombre>
			<apellidos>González Margarita</apellidos>
			<datos_contacto>
				<telefono>911257111</telefono>
				<email>marta@correo.com</email>
			</datos_contacto>
			<datos_particular>
				<nif>66666666A</nif>
				<scan_data>./content/66666666A.jpg</scan_data>
			</datos_particular>
		</datos_propi>
		<datos_gestor id_emple="e1">
			<datos_emple>
				<telefono>922222222</telefono>
				<email>pepito@inmobiliaria.correo.com</email>
			</datos_emple>
			<foto_emple>./conent/e1.jpg</foto_emple>
			<disponibilidad>
				<l-v-m>Completa</l-v-m>
				<l-v-t>Nunca</l-v-t>
				<s-m>Ocasionalmente</s-m>
			</disponibilidad>
		</datos_gestor>
		<datos_subasta>
			<puja id_puja="v1-210222200125">
				<cliente>Paquito</cliente>
				<timestamp>
					<dia>22</dia>
					<mes>Febrero</mes>
					<anio>2021</anio>
					<hora>20:01:25</hora>
				</timestamp>
				<cantidad>600</cantidad>
			</puja>
			<puja id_puja="v1-210225143537">
				<cliente>LOLI</cliente>
				<timestamp>
					<dia>25</dia>
					<mes>Febrero</mes>
					<anio>2021</anio>
					<hora>14:35:37</hora>
				</timestamp>
				<cantidad>400</cantidad>
			</puja>
		</datos_subasta>
	</inmueble>
	<inmueble>
		<datos_inmueble tipo_inmueble="Vivienda" id_inmueble="v2">
			<forma_adquisicion>Alquiler con 5 meses de fianza</forma_adquisicion>
			<precio>800</precio>
			<metros2>50</metros2>
			<ubicacion>
				<calle>Mayor, 5</calle>
				<localidad>Madrid</localidad>
				<CCAA>Comunidad de Madrid</CCAA>
				<cod_postal>28001</cod_postal>
			</ubicacion>
			<descripcion>
				<n_habitaciones>2</n_habitaciones>
				<n_banios>3</n_banios>
				<luminosidad>Baja</luminosidad>
				<terraza>No</terraza>
				<amueblado>Si</amueblado>
				<calif_energetica>C</calif_energetica>
			</descripcion>
			<fotos_inmu>
				<foto_inmu desc="PEPE">./content/v2.jpg</foto_inmu>
			</fotos_inmu>
		</datos_inmueble>
		<datos_propi id_propi="p2" tipo_propi="Particular">
			<nombre>Pepito</nombre>
			<apellidos>Pérez García</apellidos>
			<datos_contacto>
				<telefono>911111111</telefono>
				<email>pepito@correo.com</email>
			</datos_contacto>
			<datos_particular>
				<nif>55555555A</nif>
				<scan_data>./content/55555555A.png</scan_data>
			</datos_particular>
		</datos_propi>
		<datos_gestor id_emple="e2">
			<datos_emple>
				<telefono>922222222</telefono>
				<email>manuela@inmobiliaria.correo.com</email>
			</datos_emple>
			<foto_emple>./content/e2.jpg</foto_emple>
			<disponibilidad>
				<l-v-m>Completa</l-v-m>
				<l-v-t>Nunca</l-v-t>
				<s-m>Ocasionalmente</s-m>
			</disponibilidad>
		</datos_gestor>
		<datos_subasta>
			<puja id_puja="v21-210222200125">
				<cliente>Paquito</cliente>
				<timestamp>
					<dia>22</dia>
					<mes>Febrero</mes>
					<anio>2021</anio>
					<hora>20:01:25</hora>
				</timestamp>
				<cantidad>600</cantidad>
			</puja>
			<puja id_puja="v2-210225143537">
				<cliente>LOLI</cliente>
				<timestamp>
					<dia>25</dia>
					<mes>Febrero</mes>
					<anio>2021</anio>
					<hora>14:35:37</hora>
				</timestamp>
				<cantidad>400</cantidad>
			</puja>
		</datos_subasta>
	</inmueble>
	<inmueble>
		<datos_inmueble tipo_inmueble="Vivienda" id_inmueble="v3">
			<forma_adquisicion>Alquiler con 5 meses de fianza</forma_adquisicion>
			<precio>1200</precio>
			<metros2>95</metros2>
			<ubicacion>
				<calle>Mayor, 25</calle>
				<localidad>Madrid</localidad>
				<CCAA>Comunidad de Madrid</CCAA>
				<cod_postal>28001</cod_postal>
			</ubicacion>
			<descripcion>
				<n_habitaciones>3</n_habitaciones>
				<n_banios>4</n_banios>
				<luminosidad>Alta</luminosidad>
				<terraza>Sí</terraza>
				<amueblado>Si</amueblado>
				<calif_energetica>B</calif_energetica>
			</descripcion>
			<fotos_inmu>
				<foto_inmu desc="PEPE">./content/v1.jpg</foto_inmu>
			</fotos_inmu>
		</datos_inmueble>
		<datos_propi id_propi="p3" tipo_propi="Particular">
			<nombre>Manolito</nombre>
			<apellidos>García Aguado</apellidos>
			<datos_contacto>
				<telefono>919987885</telefono>
				<email>manolito@correo.com</email>
			</datos_contacto>
			<datos_particular>
				<nif>66668666A</nif>
				<scan_data>./content/66668666A.jpg</scan_data>
			</datos_particular>
		</datos_propi>
		<datos_gestor id_emple="e1">
			<datos_emple>
				<telefono>922222222</telefono>
				<email>pepito@inmobiliaria.correo.com</email>
			</datos_emple>
			<foto_emple>./content/e2.jpg</foto_emple>
			<disponibilidad>
				<l-v-m>Completa</l-v-m>
				<l-v-t>Nunca</l-v-t>
				<s-m>Ocasionalmente</s-m>
			</disponibilidad>
		</datos_gestor>
		<datos_subasta>
			<puja id_puja="v3-210222200125">
				<cliente>Paquito</cliente>
				<timestamp>
					<dia>22</dia>
					<mes>Febrero</mes>
					<anio>2021</anio>
					<hora>20:01:25</hora>
				</timestamp>
				<cantidad>600</cantidad>
			</puja>
			<puja id_puja="v3-210225143537">
				<cliente>Manuela</cliente>
				<timestamp>
					<dia>25</dia>
					<mes>Febrero</mes>
					<anio>2021</anio>
					<hora>14:35:37</hora>
				</timestamp>
				<cantidad>1000</cantidad>
			</puja>
		</datos_subasta>
	</inmueble>
	<inmueble>
		<datos_inmueble tipo_inmueble="Vivienda" id_inmueble="v5">
			<forma_adquisicion>Venta</forma_adquisicion>
			<precio>321000</precio>
			<metros2>110</metros2>
			<ubicacion>
				<calle>Villablanca, 25</calle>
				<localidad>Madrid</localidad>
				<CCAA>Comunidad de Madrid</CCAA>
				<cod_postal>28032</cod_postal>
			</ubicacion>
			<descripcion>
				<n_habitaciones>3</n_habitaciones>
				<n_banios>2</n_banios>
				<luminosidad>Media</luminosidad>
				<terraza>Sí</terraza>
				<amueblado>Si</amueblado>
				<calif_energetica>A</calif_energetica>
			</descripcion>
			<fotos_inmu>
				<foto_inmu desc="PEPE">./content/v5.jpg</foto_inmu>
			</fotos_inmu>
		</datos_inmueble>
		<datos_propi id_propi="p4" tipo_propi="Particular">
			<nombre>Ana María Margarita</nombre>
			<apellidos>Todos los Santos, de</apellidos>
			<datos_contacto>
				<telefono>911257111</telefono>
				<email>margaritamaria@correo.com</email>
			</datos_contacto>
			<datos_particular>
				<nif>88888888A.jpg</nif>
				<scan_data>./content/88888888A.jpg</scan_data>
			</datos_particular>
		</datos_propi>
		<datos_gestor id_emple="e8">
			<datos_emple>
				<telefono>922987222</telefono>
				<email>josemanuel@inmobiliaria.correo.com</email>
			</datos_emple>
			<foto_emple>"./conent/e8.jpg"</foto_emple>
			<disponibilidad>
				<l-v-m>Nunca</l-v-m>
				<l-v-t>Completa</l-v-t>
				<s-m>Ocasionalmente</s-m>
			</disponibilidad>
		</datos_gestor>
	</inmueble>
	<inmueble>
		<datos_inmueble tipo_inmueble="Vivienda" id_inmueble="v4">
			<forma_adquisicion>Venta</forma_adquisicion>
			<precio>253000</precio>
			<metros2>85</metros2>
			<ubicacion>
				<calle>Mayor, 85</calle>
				<localidad>Madrid</localidad>
				<CCAA>Comunidad de Madrid</CCAA>
				<cod_postal>28001</cod_postal>
			</ubicacion>
			<descripcion>
				<n_habitaciones>3</n_habitaciones>
				<n_banios>2</n_banios>
				<luminosidad>Media</luminosidad>
				<terraza>No</terraza>
